[project]
name = "hexlet-code"
version = "0.1.0"
description = "Task Manager"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dj-database-url>=2.3.0",
    "django>=5.1.5",
    "django-bootstrap5>=24.3",
    "django-crispy-forms>=2.1",
    "crispy-bootstrap5>=2023.10",
    "python-dotenv>=1.0.1",
    "psycopg2-binary>=2.9.9",
    "whitenoise>=6.9.0",
    "gunicorn>=23.0.0",
    "django-filter>=23.5",
    "django-allauth>=0.61.1",
    "rollbar>=1.3.0",
    "uvicorn>=0.34.0",
    "flake8>=7.1.1",
]

[project.optional-dependencies]
dev = [
    "flake8>=7.1.1",
    "pytest-django>=4.8.0",
]
test = [
    "pytest",
    "pytest-django>=4.8.0",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "Task Manager"
authors = ["Yerzhan <erzhan.sarsenov@gmail.com>"]
readme = "README.md"
packages = [
    { include = "task_manager" },
]

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.5"
django-bootstrap5 = "^24.3"
django-crispy-forms = "^2.1"
crispy-bootstrap5 = "^2023.10"
python-dotenv = "^1.0.1"
psycopg2-binary = "^2.9.9"
whitenoise = "^6.9.0"
gunicorn = "^23.0.0"
dj-database-url = "^2.3.0"
django-filter = "^23.5"
django-allauth = "^0.61.1"
rollbar = "^1.3.0"
uvicorn = "^0.34.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
pytest-django = "^4.8.0"

[tool.poetry.group.testing]
optional = true

[tool.poetry.group.testing.dependencies]
pytest = "*"
pytest-django = "^4.8.0"
