# Generated by Django 6.0.3 on 2026-03-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
