# Generated by Django 5.2.3 on 2025-07-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label'),
        ('tasks', '0002_task_tasklabelrelation_remove_tasks_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labels',
        ),
    ]
