# Generated by Django 5.2 on 2025-06-13 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_executed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.status'),
        ),
        migrations.AddField(
            model_name='tasklabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.label'),
        ),
        migrations.AddField(
            model_name='tasklabel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, through='tasks.TaskLabel', to='tasks.label'),
        ),
        migrations.AlterUniqueTogether(
            name='tasklabel',
            unique_together={('task', 'label')},
        ),
    ]
