# Generated by Django 5.2.4 on 2025-07-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="label",
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="labels", to="labels.label"
            ),
        ),
    ]
