# Generated by Django 5.1.4 on 2025-01-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='performer',
            new_name='executor',
        ),
    ]
