# Generated by Django 5.1.5 on 2025-02-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0003_labelstasksreal_tasks_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='label', through='tasks.LabelsTasksReal', to='labels.labels'),
        ),
    ]
