# Generated by Django 5.2 on 2025-05-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_executor'),
        ('tasks', '0005_remove_tasks_label_tasks_labels_alter_tasks_creator_and_more'),
    ]

    operations = [
    ]
