# Generated by Django 5.1.5 on 2025-05-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_tasks_label_tasks_labels_alter_tasks_creator_and_more'),
        ('tasks', '0008_rename_tag_to_label'),
    ]

    operations = [
    ]
