name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: False
      DATABASE_URL: sqlite:///db.sqlite3
      CI: True
      TESTING: True

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install uv and project dependencies
        run: |
          pip install uv
          uv sync

      - name: Apply migrations
        run: |
          uv run python3 manage.py migrate

      - name: Run linter and tests
        run: |
          make check

      - name: Run test coverage
        run: |
          uv run coverage run --source='.' manage.py test
          uv run coverage xml

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=darthlivesey_python-project-52
            -Dsonar.organization=darthlivesey
            -Dsonar.python.coverage.reportPaths=coverage.xml