# Generated by Django 5.2 on 2025-05-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_status_options_alter_status_name'),
        ('statuses', '0002_alter_statuses_name'),
    ]

    operations = [
    ]
